 sudo python3 GUI_E2box.py
IMU 0 start time : 200813_170834
IMU 0 end :  120.52309823036194
IMU 0 start time : 200813_171035
IMU 0 end :  31.464033365249634
IMU 0 start time : 200813_171107
IMU 0 end :  31.026404857635498
IMU 0 start time : 200813_171138
IMU 0 end :  32.64013910293579
IMU 0 start time : 200813_171210
IMU 0 end :  32.36486744880676
IMU 0 start time : 200813_171243
IMU 0 end :  32.56317853927612
IMU 0 start time : 200813_171315
IMU 0 end :  32.69050574302673
IMU 0 start time : 200813_171348
IMU 0 end :  34.54408502578735
IMU 0 start time : 200813_171423
IMU 0 end :  33.08195757865906
IMU 0 start time : 200813_171456
IMU 0 end :  33.45034050941467
IMU 0 start time : 200813_171529
IMU 0 end :  33.74994206428528
IMU 0 start time : 200813_171603
IMU 0 end :  32.55298066139221
IMU 0 start time : 200813_171635
IMU 0 end :  32.9530143737793
IMU 0 start time : 200813_171708
IMU 0 end :  61.7454514503479
IMU 0 start time : 200813_171810
IMU 0 end :  55.34132647514343
IMU 0 start time : 200813_171905
IMU 0 end :  55.455970764160156
IMU 0 start time : 200813_172001
IMU 0 end :  48.62726545333862
IMU 0 start time : 200813_172049
IMU 0 end :  41.45907115936279
IMU 0 start time : 200813_172131
^[[AIMU 0 end :  52.52318620681763
IMU 0 start time : 200813_172223
IMU 0 end :  42.941309213638306
IMU 0 start time : 200813_172306
IMU 0 end :  48.26116180419922
IMU 0 start time : 200813_172355
^CTraceback (most recent call last):
  File "GUI_E2box.py", line 227, in <module>




===================================================

s/GUI_sws $ ^C
pi@raspberrypi:~/Desktop/sws/GUI_sws $ sudo python GUI_E2box__.py
IMU 0 start time : 200813_172636
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "GUI_E2box__.py", line 185, in GUI
    var[2].set(data[10]/1000)
IndexError: index out of range

^CTraceback (most recent call last):
  File "GUI_E2box__.py", line 230, in <module>
    threads[iter].join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
pi@raspberrypi:~/Desktop/sws/GUI_sws $ ^C
pi@raspberrypi:~/Desktop/sws/GUI_sws $ sudo python GUI_E2box__.py
IMU 0 start time : 200813_173103
IMU 0 end :  473.159006357193
IMU 0 start time : 200813_173856
^CTraceback (most recent call last):
  File "GUI_E2box__.py", line 230, in
